### PR TITLE
Migrate to Typescript

### LINKED ISSUE #13: Add support to Typescript
To be able to use this lib on a Typescript project, the developer has to add a declaration module file.

It was better if the lib was already packaged with the declaration files.

### PR DESCRIPTION
**Pull request by marcelorubim**
Fix #13

The previous PR was just adding the declaration files for the project. As those files would need to be changed manually to reflect the code, I've decided to implement better support.

This one adds full support to Typescript as I migrated the code to TS.

### CODE REVIEW

**Comment by eabili0** [comment]
@marcelorubim, thank you for your contribution. We'll proceed with some tests now to assure your modifications to the lib does not impact other users express apps written in JS. @KarineValenca will be leading those tests

**Comment by KarineValenca** [comment]
@marcelorubim I found a problem while I was trying to import the library. 
Using the current way of importing: `const Monitor` with your new code, I faced the error: `TypeError: Monitor.init is not a function`

I saw you changed the way of importing the lib from:
`const Monitor`
to 
`const { Monitor }`

Since it is a breaking change, can you find a way to export the lib in order to both kinds of imports be allowed?

**Comment by marcelorubim** [comment]
> @marcelorubim I found a problem while I was trying to import the library.
> Using the current way of importing: `const Monitor` with your new code, I faced the error: `TypeError: Monitor.init is not a function`
> 
> I saw you changed the way of importing the lib from:
> `const Monitor`
> to
> `const { Monitor }`
> 
> Since it is a breaking change, can you find a way to export the lib in order to both kinds of imports be allowed?

Hi, @KarineValenca!

Do you mean the change in the example.js?

Before:
```js
const Monitor = require('../lib/monitor')
```
After:
```js
const { Monitor } = require('../dist/')
```

I just changed the import to reflect the example in the README. To import the old way on the example.js, you can do this way:

```js
const Monitor = require('../dist/lib/monitor')
```

The projects importing this lib still imports the same way:

```js
import { Monitor } from "express-monitor";

```

**Comment by KarineValenca** [comment]
@marcelorubim you're right! I tested it again and the import from npm is working properly! 

Thank you very much. I'll accept the PR.

**Pull request merged**
